fix issue that is causing the isEncrypted.test to fail (#2249)
PR broke the test build.

https://github.com/HereNotThere/harmony/pull/2238/files/7c6cabb6c65f96ac1296a51db4bcadaa074b41cb#diff-1283442167a0b82b7b8dc55853331770e5307c38543650c7ea3e0962e6f675be

```
tests/integration/isEncrypted.test.tsx
  ● Test suite failed to run

    tests/integration/isEncrypted.test.tsx:19:35 - error TS2554: Expected 2 arguments, but got 1.

    19         const spaceId = await bob.createSpaceRoom({
                                         ~~~~~~~~~~~~~~~~~
    20             name: "bob's space",
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    21             visibility: RoomVisibility.Public,
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    22         })
       ~~~~~~~~~~

      src/client/ZionClient.ts:462:9
        462         networkId: string | undefined,
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        An argument for 'networkId' was not provided.
    tests/integration/isEncrypted.test.tsx:26:37 - error TS2554: Expected 2 arguments, but got 1.

     26         const channelId = await bob.createChannelRoom({
                                            ~~~~~~~~~~~~~~~~~~~
     27             name: "bob's channel",
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ... 
     30             roleIds: [],
        ~~~~~~~~~~~~~~~~~~~~~~~~
     31         })
        ~~~~~~~~~~

      src/client/ZionClient.ts:579:9
        579         networkId: string | undefined,
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        An argument for 'networkId' was not provided.
```