Fix error overlay to show thrown error instead of undefined (reading 'frame') (#1990)
The error overlay always shows the same error

```
Cannot read properties of undefined (reading 'frame')
TypeError: Cannot read properties of undefined (reading 'frame')
    at new ErrorOverlay (http://localhost:3001/@vite/client:143:30)
    at showErrorOverlay (http://localhost:3001/src/main.tsx?t=1680289958673:37:21)
    at http://localhost:3001/src/main.tsx?t=1680289958673:43:9
```

This code checks the error first for an error property, otherwise just
uses the error as an error.

It should preserve backwards functionality, if there is an error in the
error it will still display that error.

Test Plan:
added `throw new Error(‘Please Display Me!!!”)` to the login button, saw
the real error in the popup