Add a jest-setup to the sdk tests that mocks some viem things (#4087)
In order to import and use Permission from @river/web3 in the sdk tests
we need to do this mock. If we don’t we get:

```
  ● Test suite failed to run

    SyntaxError: The requested module './encodeLabelhash.js' does not provide an export named 'encodeLabelhash'

      at Runtime.linkAndEvaluateModule (../../node_modules/jest-runtime/build/index.js:699:5)
```