fix: update arg names to match contracts (#3914)
### Description

Update arg names to match contracts for recent changes. Followup PR will
add `yarn build` step to CI so we can catch these errors during CI.

```
# before this pr
yarn typecheck
➜  subgraph git:(main) ✗ yarn typecheck
src/index.ts:153:53 - error TS2339: Property 'collectPosterFeeToSpace' does not exist on type '{ posterFeeBps: number; forwardPosterFee: boolean; }'.

153                 collectPosterFeeToSpace: event.args.collectPosterFeeToSpace,
                                                        ~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:163:53 - error TS2339: Property 'collectPosterFeeToSpace' does not exist on type '{ posterFeeBps: number; forwardPosterFee: boolean; }'.

163                 collectPosterFeeToSpace: event.args.collectPosterFeeToSpace,
                                                        ~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:256:38 - error TS2339: Property 'treasury' does not exist on type '{ token: `0x${string}`; protocol: `0x${string}`; poster: `0x${string}`; protocolAmount: bigint; posterAmount: bigint; }'.

256                 treasury: event.args.treasury,
                                         ~~~~~~~~

src/index.ts:258:44 - error TS2339: Property 'treasuryAmount' does not exist on type '{ token: `0x${string}`; protocol: `0x${string}`; poster: `0x${string}`; protocolAmount: bigint; posterAmount: bigint; }'.

258                 treasuryAmount: event.args.treasuryAmount,
                                               ~~~~~~~~~~~~~~


Found 4 errors in the same file, starting at: src/index.ts:153
```

### Changes

<!-- List the specific changes made in this PR, for example:
- Added/modified feature X
- Fixed bug in component Y
- Refactored module Z
- Updated documentation
-->

### Checklist

- [ ] Tests added where required
- [ ] Documentation updated where applicable
- [ ] Changes adhere to the repository's contribution guidelines