Fix subgraph remove Bun support (#4746)
### Description

Fixes bun<>ponder incompatibility issue:

```
TypeError: Attempted to assign to readonly property. occurred in '/river/node_modules/.bun/ponder@0.13.14+791ac4711a6ed4f8/node_modules/ponder/src/graphql/middleware.ts:87:5' while handling a 'POST' request to the route '/'
```

issue documented:

https://github.com/ponder-sh/ponder/issues/442
https://github.com/oven-sh/bun/issues/8302
https://github.com/oven-sh/bun/pull/11082

We replace bun with node.js/npx in this pr in the image which fixes the
issue preventing the subgraph-api from loading the schema and serving
requests.

We can upgrade to a ponder1.15 in a future pr and test the subgraph
before rolling out bun support again. At any rate though bun's speed
would be good, subgraph is mostly I/O bound and is long running so
doesn't really benefit from faster cold start times and CPU performance
improvements that bun offers.

### Changes

<!-- List the specific changes made in this PR, for example:
- Added/modified feature X
- Fixed bug in component Y
- Refactored module Z
- Updated documentation
-->

### Checklist

- [ ] Tests added where required
- [ ] Documentation updated where applicable
- [ ] Changes adhere to the repository's contribution guidelines